### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by lucasyoboy** [Mokkapps/gaming-news-aggregator#2]
When I enter npm start, this following error happen:

> gaming-news-aggregator@0.1.0 start /var/www/html/api/gaming-news-aggregator
> node index.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/var/www/html/api/gaming-news-aggregator/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gaming-news-aggregator@0.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gaming-news-aggregator@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-23T12_45_16_012Z-debug.log

**Comment by Mokkapps** [comment]
`index.js` does not exist anymore, it is replaced by `start.js` 

So you should change: `"start": "node start.js"`

**Comment by lucasyoboy** [comment]
Ok thanks

**Comment by lucasyoboy** [comment]
Please update the project. Its useful

**Comment by Mokkapps** [comment]
> Please update the project. Its useful

Unfortunately, I don't have the time to maintain this project 🥲
